# Use a Rust base image with development tools
FROM rust:1.85

# Set the working directory
WORKDIR /app/api-gateway

# Copy only the manifest files (Cargo.toml and Cargo.lock)
COPY api-gateway/Cargo.toml .
COPY api-gateway/Cargo.lock .
COPY api-gateway/src ./src
# Install dependencies
RUN cargo fetch

# Copy the rest of the source code
# COPY api-gateway/src ./src

# Install debugging tools (optional)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gdb \
    lldb \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables for development
ENV RUST_LOG=debug
ENV RUST_BACKTRACE=1

# Expose the application port
EXPOSE 8500

# Default command for development mode
CMD ["cargo", "run"]