services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortener_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - app-network
    healthcheck:
      test: ["CMD","rabbitmq","status"] # rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  shortener-service:
    build:
      context: .
      dockerfile: shortener-service/Dockerfile
    container_name: shortener-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/shortener_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./common:/app/common

  redirect-service:
    build:
      context: .
      dockerfile: redirect-service/Dockerfile
    container_name: redirect-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/shortener_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      REDIS_URL: redis://redis:6379
    networks:
      - app-network
    ports:
      - "8081:8081"
    volumes:
    - ./common:/app/common
  
  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: user-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/shortener_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      ASPNETCORE_URLS: http://*:8082
    networks:
      - app-network
    ports:
      - "8082:8082"

  api-gateway:
      build:
        context: .
        dockerfile: api-gateway/Dockerfile.dev # Use a separate Dockerfile for development
      volumes:
        - ./api-gateway:/app/api-gateway # Mount the source code as a volume
      environment:
        - RUST_LOG=debug
        - RUST_BACKTRACE=1
        - USER_SERVICE_URL=http://user-service:8082/api
      ports:
      - "8500:8500"
      tty: true # Keep the container running for interactive use
      stdin_open: true # Enable interactive input
      networks:
        - app-network
    
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge